name: "Add Product"
description: "Submit a new product to appear on the Smart Home Finds webapp."
title: "Add product: "
labels: ["product"]
body:
  - type: markdown
    attributes:
      value: |
        **Tip (photo):** you can *drag & drop* an image into this form (or paste a direct image URL).
        If you upload an image, GitHub will generate a link like `https://user-images...` that you can paste into **Image URL**.

  - type: input
    id: title
    attributes:
      label: Title
      description: Product name shown on the card
      placeholder: "Set of 2 Metal Wall Sconce Candle Holders"
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Candles
        - Wall Art
        - Furniture
        - Gifts
        - Accessories
        - Kitchen
        - Bathroom
        - Lighting
        - Smart
    validations:
      required: true

  - type: input
    id: pin
    attributes:
      label: Pinterest Pin URL
      description: Required (the main reference)
      placeholder: "https://pin.it/xxxx or https://www.pinterest.com/pin/..."
    validations:
      required: true

  - type: input
    id: dest
    attributes:
      label: Destination / Affiliate URL
      description: Optional (Amazon / shop link)
      placeholder: "https://amzn.to/xxxxxxx"
    validations:
      required: false

  - type: input
    id: image
    attributes:
      label: Image URL
      description: Optional — best: direct image link (i.pinimg.com) or a GitHub uploaded image link (user-images...)
      placeholder: "https://i.pinimg.com/...jpg"
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Optional — comma separated
      placeholder: "modern, minimalist, cozy, farmhouse"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Short Notes
      description: Optional — why it's good / where to use it / gift idea…
      placeholder: "Why it’s good / where to use it / gift idea…"
    validations:
      required: false
