name: Add Product
description: Add a new product to the Smart Home Finds webapp
title: "Add product: "
labels: ["add-product"]
body:
  - type: input
    id: pin_url
    attributes:
      label: Pinterest Pin URL
      placeholder: "https://pin.it/..."
    validations:
      required: true

  - type: input
    id: affiliate_url
    attributes:
      label: Destination / Affiliate URL (optional)
      placeholder: "https://amzn.to/..."

  - type: input
    id: image_url
    attributes:
      label: Image URL (optional)
      description: "Direct image URL (e.g., i.pinimg.com/...)"
      placeholder: "https://i.pinimg.com/..."

  - type: input
    id: title
    attributes:
      label: Title (optional)
      placeholder: "Leave blank to use issue title"

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Candles
        - Wall Art
        - Furniture
        - Gifts
        - Accessories
        - Kitchen
        - Bathroom
      default: 0
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags (comma separated)
      placeholder: "cozy, minimalist, farmhouse"
