name: "➕ Add Product"
description: "Add a new product to Smart Home Finds (Pinterest + Affiliate link + image)."
title: "Product: "
labels: ["product"]
body:
  - type: input
    id: pin_url
    attributes:
      label: "Pinterest Pin URL"
      placeholder: "https://pin.it/xxxxxxxx"
    validations:
      required: true

  - type: input
    id: destination_url
    attributes:
      label: "Destination / Affiliate URL (optional)"
      placeholder: "https://amzn.to/xxxxxxx"
    validations:
      required: false

  - type: input
    id: image_url
    attributes:
      label: "Image URL (optional)"
      placeholder: "https://i.pinimg.com/...jpg"
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: "Category"
      options:
        - Candles
        - Wall Art
        - Furniture
        - Lighting
        - Gifts
        - Accessories
        - Kitchen
        - Bathroom
        - Storage
        - Smart Home
        - Outdoor
        - Other
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: "Tags (comma separated)"
      placeholder: "modern, minimalist, cozy"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "Short Notes (optional)"
      placeholder: "Why it’s good / where to use it…"
    validations:
      required: false
